Fix Docker instructions in the main README
solid/node-solid-server pull request #1473
Opened 2020-09-03 16:29 UTC by vemonet

Remove outdated instructions about running using Docker from README.md, and redirect the user to the docker-images/README documentation page

2020-09-04 18:44 UTC, angelo-v approved these changes

2020-09-04 19:15 UTC, bourgeoa commented
There are 2 ways to use docker :
- with the docker-image using some env parameters
- using the Dockerfile and a config.json with extensive parameters

I personally only use the Dockerfile which can also be used to test NSS modifications.

The documentation should reflect that, and not only the docker-image way.

2020-09-04 19:44 UTC, angelo-v commented
You could mount a config.json to the production image as well. The dockerfile is good for development while the image is production ready.

2020-09-04 19:51 UTC, bourgeoa commented
I don't think the documentation relates only to production ready server. That's why both approach should be maintained.

2020-09-04 20:23 UTC, angelo-v commented
You are right @bourgeoa the readme currently mixes both and we should reflect that for docker as well, just separate both variants clearly by subsections.

2020-09-04 20:28 UTC, angelo-v requested changes

2020-09-04 20:28 UTC, angelo-v commented on README.md
> +See the [documentation to run Solid using docker and docker-compose](https://github.com/solid/node-solid-server/tree/master/docker-image).
```suggestion

### Production usage

See the [documentation to run Solid using docker and docker-compose](https://github.com/solid/node-solid-server/tree/master/docker-image).
```

2020-09-04 20:28 UTC, angelo-v commented on README.md
> -
Let's restore this section under the headline `development usage`

2020-09-04 20:28 UTC, angelo-v commented on README.md
> -docker pull nodesolidserver/node-solid-server
Instead of pulling the prod image this should instruct to build the Dockerfile

2020-09-05 12:52 UTC, vemonet commented
Thanks for the feedback @angelo-v 

@bourgeoa I put back the [previous documentation](https://github.com/vemonet/node-solid-server/tree/fix/docker-docs#development-usage) describing the use of the Dockerfile at the root of the repository under the `Development usage` section

2020-09-08 17:21 UTC, bourgeoa commented
OK for me

2020-09-08 17:21 UTC, merged

2020-09-10 06:48 UTC, angelo-v reviewed
Nice!