Added correct email address to reach out
solid/node-solid-server pull request #1687
Opened 2022-04-04 05:15 UTC by alceil

Solves #1560

2022-04-04 19:03 UTC, bourgeoa requested changes

2022-04-05 04:40 UTC, alceil commented on README.md
> +- Reach out to Alain at alain.bourgeois10@gmail.com to become more involved in maintaining Node Solid Server
got it

2022-04-05 04:42 UTC, alceil commented
Added the requested changes please have a look @bourgeoa

2022-04-05 06:14 UTC, bourgeoa approved these changes

2022-04-15 13:21 UTC, closed without merging

2022-04-15 13:22 UTC, bourgeoa commented
Has been updated